### ISSUE TITLE
Installing on clean phpbb 3.1 throws error 

### ISSUE THREAD

**Issue by rnesius** [phpbbmodders/phpbb-3.1-ext-adduser#14]
When enabling the extension, phpbb throws the following error:  

> Something went wrong during the request and an exception was thrown. The changes made before the error occurred were reversed to the best of our abilities, but you should check the board for errors.
The config setting "adduser_version" unexpectedly does not exist."

I was able to figure out that the error was coming out of ... migrations/v11/version_11.php 

```php
public function update_data()
        {
                return array(
                        array('config.update', array('adduser_version', '1.0.1')),
                );
        }
```

The config.update directive appears to be attempting to update the 'adduser_version' property/attribute, and it doesn't exist yet.  Changing *config.update* to *config.add* actually results in the error going away. But I'm not sure if the module was working - I couldn't find a way to add a user anywhere in the ACP.  I'm wondering if the real issue the hooks in ...migrations/v10/install_adduser.php aren't firing first?  

Any thoughts?

**Comment by RMcGirr83** [comment]
Can't reproduce.  Is this an update or a clean install?

**Comment by rnesius** [comment]
Thanks so much for the fast response and trying to help reproduce.  I'm on phpBB 3.1.2 I think...  I'm working on getting more information. I did disable the one other extension I had installed and retried, and got the error again. 

I'm setting up a forum at siteground.com for my WoW guild and don't have full access to the web server logs there.  I'm working on getting some more information since I do know someone who might be able to get them for me.  

I did notice that phpBB installer appears to be wrapped by something called softaculous... Maybe it's their packaging of phpBB that is contributing to the issue.  Since I'm a first-time user, how do I know if the mod is working? Should I see an option under "manage users" somewhere?

**Comment by rnesius** [comment]
I copied the V10 *update_data* callback into *version_11.php* and everything's working now. So somehow v10's hooks are not being triggered.  I'm trying to get more data.

**Comment by rnesius** [comment]
I'll try your patches tonight.

**Comment by rnesius** [comment]
Looks like you fixed it.  Nice work!
